### ISSUE TITLE
Category/Description/Type text at the top of every Action and Condition page

### ISSUE THREAD

**Issue by djoume** [trywilco/wilco-docs#82]
**Describe the bug**

All "actions" and "conditions" page include an un-formatted line at the top, see for example:

![Screenshot from 2023-02-16 15-50-35](https://user-images.githubusercontent.com/34644/219486194-03fc5249-d435-45d9-91d3-32c31eea2d95.png)

I'm not sure what the purpose of those field is, maybe they should be part of the front matter?

**To Reproduce**
1. Go to any actions or conditions page, for instance: https://dev.trywilco.com/docs/building-your-quest/actions/newrelic-configure-with-key.html
2. Look at the top of the page just under the main header

**Expected behavior**
Either those fields should be hidden or they should be properly formatted (e.g as part of an unordered list)

**Screenshots**

See above

**Comment by EtiNoked** [comment]
Thank you for your feedback! The issue was resolved.
